#!/usr/bin/env php
<?php
declare(strict_types=1);

namespace Haku;

error_reporting(E_ALL & ~E_NOTICE);

define('HAKU_ROOT_PATH', __DIR__ . DIRECTORY_SEPARATOR);
define('HAKU_PHP_VERSION', '8.3.0');

if (version_compare(PHP_VERSION, HAKU_PHP_VERSION, '<')) {
	echo sprintf("Haku requires PHP %s, version %s installed.", HAKU_PHP_VERSION, PHP_VERSION);
	exit;
}

try
{
	require_once implode(DIRECTORY_SEPARATOR, [
		rtrim(HAKU_ROOT_PATH, DIRECTORY_SEPARATOR),
		'vendor', 'Haku', 'bootstrap.php'
	]);

	autoloadResolver();

	$engine = new Console\Engine();

	$engine->registerCommand(new Console\Commands\Init());
	$engine->registerCommand(new Console\Commands\Version());
	$engine->registerCommand(new Console\Commands\Serve());
	$engine->registerCommand(new Console\Commands\Routes());
	$engine->registerCommand(new Console\Commands\Test());
	$engine->registerCommand(new Console\Commands\Make());

	$engine->run();

}
catch(\Throwable $throwable)
{
	print_r($throwable);
	exit -1;
}
finally
{
	exit;
}
