#!/usr/bin/env php
<?php
declare(strict_types=1);

error_reporting(E_ALL & ~E_NOTICE);

define('HAKU_ROOT_PATH', __DIR__ . DIRECTORY_SEPARATOR);
define('HAKU_PHP_VERSION', '8.3.0');

if (version_compare(PHP_VERSION, HAKU_PHP_VERSION, '<')) {
	echo sprintf("Haku requires PHP %s, version %s installed.", HAKU_PHP_VERSION, PHP_VERSION);
	exit;
}

try
{
	echo "Hello from haku!";
	exit;
}
catch(\Throwable $throwable)
{
	print_r($throwable);
	exit -1;
}
finally
{
	exit;
}
